server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
#    password: gabriela
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
    password: 34a32a687974e3b06fcb2dfb47ed23f13106b199d41ad2b54ce4d23984781523
    url: jdbc:postgresql://ec2-176-34-105-15.eu-west-1.compute.amazonaws.com:5432/d7kes16vrlnf4u
    username: ogmoaildxvhcpo

  mail:
    host: smtp.gmail.com
    port: 465
    username: bureaucracyhacks@gmail.com
    password: proiectip
    protocol: smtp


    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
      ssl.enable: true
